# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98707e9e5904d2b5832489f49ef84643783270553bcc50be216e246750225708d4bed0a194d72c003ea92fca0aa6f6eccbc11c478bcf95db853aa6e5388d3b44

test:
  secret_key_base: a7f7822dd426afa6065d8d72b955346820f9706e820d42e8c2863c179d4f173e2b8f998351363b3ae546a91a3d36ec42d45a073cc17a6d52bbb22f5010704820

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
